### ISSUE TITLE
Interesting average purchase time

### ISSUE THREAD

**Issue by sos0** [protopizza/ApIsOp#12]
Alistar: Bronze 5.11 Zhonyas at 7 minutes

**Comment by sos0** [comment]
Aatrox: Bronze 5.11
Blasting Wand
Average purchase @ approx. 2 minutes

**Comment by sos0** [comment]
Hecarim: Unranked 5.11
Enchantment: Homeguard
Average purchase @ approx. 3 minutes

**Comment by protopizza** [comment]
I believe I've fixed this. The divisor for average time bought was set to matches played, rather than the number of times the item was bought. So if an item was not bought often it had its buy time divided by a large factor.
