### ISSUE TITLE
Ranked duplicate champions

### ISSUE THREAD

**Issue by protopizza** [protopizza/ApIsOp#25]
Currently we are allowed to select the same champion on both sides as this is legal in normal matches. But it doesn't exist in ranked matches and we don't have any enforcement on this. Stefan brought this up actually. We can still allow and display the results or disallow prediction data for ranked matches.

My opinion is that we can still display but put a warning that says "this team comp is invalid in ranked due to duplicate champion" or something.

**Comment by sos0** [comment]
Agreed solution: add disclaimer warning at filter UI for duplicate champions
