### ISSUE TITLE
Dataset needed:

### ISSUE THREAD

**Issue by sos0** [protopizza/ApIsOp#28]
graph type: item (item#.json)
x-axis: timeline.
y-axis: champions.
displaying average magic damage per timeframe.

json example:
https://daviscsbaes.slack.com/files/so/F09G1HZCN/ideal_json.js

**Comment by protopizza** [comment]
magic damage per timeframe data isn't available in the match data. we are going with a different data viz (relevant commit hash for the data: bfb9790951eac739e21714b37285d58ebb27a444 )
